import { test, expect, type Page } from '@playwright/test';
import { eq } from 'drizzle-orm';
import { db } from '../lib/db/drizzle';
import { activityLogs, aiAnalyses, events, sites, users } from '../lib/db/schema';
import { generateSiteKey } from '../lib/analytics/keys';
import { DEMO_EMAIL, DEMO_PASSWORD } from '../lib/demo';

const REPORT = {
  summary: 'A short summary of where the site stands.',
  overallAssessment: 'needs_attention',
  recommendations: [
    {
      title: 'Add a meta description to /pricing',
      category: 'technical_seo',
      priority: 'high',
      finding: 'The pricing page has no meta description.',
      evidence: '/pricing took 72 visitors and its metaDescription is empty',
      action: 'Write a 150-character description.',
      affectedPaths: ['/pricing']
    },
    {
      title: 'Link the homepage to the docs',
      category: 'content',
      priority: 'low',
      finding: 'The homepage has no internal links.',
      evidence: 'internalLinks 0 on /',
      action: 'Add a navigation menu.',
      affectedPaths: []
    }
  ],
  dataGaps: ['Search rankings behind the google.com visitors.']
};

let ownerEmail: string;
let siteId: number;
let ownerId: number;

test.beforeAll(async () => {
  ownerEmail = `insights-${Date.now()}@example.test`;
});

test.afterAll(async () => {
  // Sites cascade to events and analyses. Activity logs reference the user and do NOT cascade —
  // by design, since an audit trail that vanishes when a row is removed is not an audit trail —
  // so they have to go before the user can.
  if (siteId) await db.delete(sites).where(eq(sites.id, siteId));
  if (ownerId) {
    await db.delete(activityLogs).where(eq(activityLogs.userId, ownerId));
    await db.delete(users).where(eq(users.id, ownerId));
  }
});

async function signUp(page: Page, email: string) {
  await page.goto('/sign-up');
  await page.fill('input[name="email"]', email);
  await page.fill('input[name="password"]', 'a-long-enough-password');
  await page.click('button[type="submit"]');
  await expect(page).toHaveURL(/\/dashboard/);
}

test.describe('insights', () => {
  test('a stored report renders with its evidence inline', async ({ page }) => {
    await signUp(page, ownerEmail);

    const [owner] = await db.select().from(users).where(eq(users.email, ownerEmail)).limit(1);
    ownerId = owner.id;

    const [site] = await db
      .insert(sites)
      .values({
        userId: ownerId,
        name: 'Insights site',
        domain: `insights-${Date.now()}.example`,
        siteKey: generateSiteKey()
      })
      .returning();
    siteId = site.id;

    await db.insert(events).values({
      siteId,
      path: '/',
      referrerDomain: null,
      visitorHash: 'a'.repeat(64)
    });

    await db.insert(aiAnalyses).values({
      siteId,
      userId: ownerId,
      model: 'deepseek-v4-pro',
      inputTokens: 3126,
      outputTokens: 6984,
      costMicros: 7436,
      payload: REPORT
    });

    await page.goto(`/dashboard/sites/${siteId}/insights`);

    await expect(page.getByText('Needs attention')).toBeVisible();
    await expect(page.getByText(REPORT.summary)).toBeVisible();

    // Evidence must be visible on the page as rendered — not behind a toggle, a details element
    // or a hover. It is the only thing separating this from generic SEO advice.
    for (const rec of REPORT.recommendations) {
      await expect(page.getByText(rec.title)).toBeVisible();
      await expect(page.getByText(rec.evidence)).toBeVisible();
      await expect(page.getByText(rec.action)).toBeVisible();
    }

    // The data gaps section, and the note that this is model-generated.
    await expect(page.getByText(/what this could not answer/i)).toBeVisible();
    await expect(page.getByText(REPORT.dataGaps[0])).toBeVisible();
    await expect(page.getByText(/generated by a language model/i)).toBeVisible();

    // Cost and model are shown, so the reader knows what was spent on their behalf.
    await expect(page.getByText(/deepseek-v4-pro/).first()).toBeVisible();
    await expect(page.getByText(/\$0\.0074/).first()).toBeVisible();

    // Having just been created, the report is inside the reuse window, so the page explains that
    // rather than offering a control that would refuse.
    await expect(page.getByText(/analysed within the last 24 hours/i)).toBeVisible();
    await expect(
      page.getByRole('button', { name: /generate a new analysis anyway/i })
    ).toBeVisible();
  });

  test('the demo account is told why it cannot generate', async ({ page }) => {
    await page.goto('/sign-in');
    await page.fill('input[name="email"]', DEMO_EMAIL);
    await page.fill('input[name="password"]', DEMO_PASSWORD);
    await page.click('button[type="submit"]');
    await expect(page).toHaveURL(/\/dashboard/);

    // The sample site: two reasons apply, and the page must state one rather than showing a
    // button that fails.
    const [sample] = await db.select().from(sites).where(eq(sites.isSample, true)).limit(1);
    await page.goto(`/dashboard/sites/${sample.id}/insights`);

    await expect(page.getByText(/cannot generate analyses/i)).toBeVisible();
    await expect(
      page.getByRole('button', { name: /generate/i })
    ).toHaveCount(0);
  });

  test('insights for another account\'s site 404s', async ({ browser }) => {
    const context = await browser.newContext();
    const page = await context.newPage();
    await signUp(page, `stranger-${Date.now()}@example.test`);

    const response = await page.goto(`/dashboard/sites/${siteId}/insights`);
    expect(response?.status()).toBe(404);

    await context.close();
  });
});
